<div align="center">
  <h1>Cadenas de Márkov</h1>
  <p>
    Autores:<br />
    Sergio Andrés Majé Franco<br />
    Marleny Rojas Gómez
  </p> 
  <p>
    Docente:<br />
    Dr. Jesús Emilio Pinto Lopera 
  </p>
  <p>
    Universidad de la Amazonia<br />
    Facultad de Ingeniería<br />
    Programa Ingeniería de Sistemas<br />
    Florencia - Caquetá<br />
    2023
  </p>
</div>

## Tabla de Contenido

1. Introducción
2. Desarrollo Metodológico
    1. Desarrollo Teórico
      1. Cadenas de Márkov
      2. Homogéneas y no homogéneas
      3. Matriz de Transición 
      4. Distribución Binomial
    2. Desarrollo Computacional
      1. Función Binomial
      2. Matríz de Transición
3. Problemas
4. Resultados
  1. Ejemplo con 3 usuarios
  2. Ejemplo con 4 usuarios
  3. Ejecicio dinámico
5. Conclusiones
6. Referencias

## Tabla de Formulas

1. Formula 1. Propiedad Márkoviana
2. Formula 2. Para todo n y para cualquier i,j
3. Probabilidad de estado $i$ a $j$ en n unidades de tiempo
4. Probabilidad al dar 1 paso de $i$ a $j$
5. Probabilidad en n pasos
6. Agrupación de la matríz de transición
7. Distribución Binomial

## Tabla de Tablas

1. Tabla 1. Matríz de transición con 3 usuarios
2. Tabla 2. Matríz de transición con 4 usuarios
3. Tabla 3. Matríz de transición Dinámica


## 1. Introducción


Como bien sabemos, hoy en día es común ver en los diferentes espacios públicos, un porcentaje de la humanidad que presentan diversos problemas de cualquier ámbito, los cuales involucran poder satisfacer las necesidades de cada uno de ellos. Existen métodos que por medio de observaciones determinan una variedad de resultados, donde cada uno presenta su respectiva probabilidad, dependiendo únicamente del resultado de la fase anterior. Por lo tanto, haciendo honor al matemático Andrei Andreyevich, quien creo este método, logrando resaltar este importante proceso, el cual intervienen ciertas variables aleatorias indexadas transcurridas en el tiempo y así se denominan cadenas de Márkov. De tal forma, la probabilidad de que un evento suceda depende del evento anterior, permitiendo predecir su comportamiento a corto y a largo plazo.

En los siguientes apartados daremos inicio a la estructura sobre las cadenas de Márkov, conocer sus procesos, formulas y demás desarrollo que nos permitira enfatizar la problematica escogida. 


## 2. Desarrollo Metodológico

### 2.1. Desarrollo Teoríco

#### 2.1.1. Cadenas de Márkov

Una cadena de markov representa los procesos en los cuales la sucesión de variables aleatorias, evolucionan en función de otra variable. Esta herramienta permite analizar los conjuntos de variables con efectos aleatorios, los cuales toman como nombre proceso estocástico. Permiten emplearla como una secuencia ${X}1$, $ {X}2$, $ {X}3$… de las respectivas variables aleatorias, donde el valor de $ {\ X}_n $  representa al estado del proceso con respecto en el tiempo n. A continuación de anexa la propiedad de la Cadena de Márkov:



$$ P\ (X_{n+1}=\ X_{n+1\ \ |}\ X_n\ =\ x_n{,\ X}_{n\ -1\ }=\ x_{n\ -\ 1,...,\ }X_{2\ \ }=\ x_{2,\ }X_{1\ }=\ x_1)\ =\ P\ (X_{n+1}=\ X_{n+1\ \ |}{\ X}_n) $$

<div align="center">
    Formula 1. Propiedad Márkoviana
</div>

 $ {x}i$ : Representa la estado del proceso en el instante $i$

 La propiedad de las cadenas de Márkov, deducen que las transiciones entre los estados, solo se pueden producir entre sus estados vecinos, donde solo se puede legar al estado $i$ partiendo de estado $i - 1$ y el estado $i +1$.

#### 2.1.2. Cadenas Homogéneas y no Homogéneas

De la manera homogénea, una cadena de markov representa si la probabilidad de ir el estado $i$ al estado $j$, nos dice que en un paso no depende del tiempo en el que está transcurriendo la cadena, por lo tanto: 
 
 $$ P\ (X_{n-1\ \ \ }=\ i)\ =\ P\ (\ X_0\ =\ i\ ) $$

 <div align="center">
    Formula 2. Para todo n y para cualquier $i$, $j$
</div>

Para deducir cuando la cadena de márkov es no homogénea, se concluye que si para algunas de las parejas de estados en su determinado tiempo n, la propiedad dicha anteriormente no se logra cumplir.


#### 2.1.3. Matriz de Transición

La matriz de probalidades de transición representa una matriz estocástica, donde la suma de las filas es igual a 1 y debe contener el mismo número de filas y columnas

 $$ P_{ij^{(n)}}= Pr (X_n =\ j\ |\ X_n\ =\ j\ |\ X_0\ =\ i\ ) $$

  <div align="center">
    Formula 3. Probabilidad de estado $i$ a $j$ en n unidades de tiempo
</div>

La probabilidad de transición, a dar un paso se pasa por alto el superíndice, obteniendo lo siguiente: 

$$ P_{ij}= Pr (X_1 = j | X_0\ =\ i\ ) $$

 <div align="center">
    Formula 4. Probabilidad al dar 1 paso de $i$ a $j$
</div>


Continuando con lo anterior, las probabilidades de transición en n pasos, es decir para cualquier $k$ diciendo tal que $0< k < n$ se cumple que:

$$ P_{ij}^{(n)}=\ \sum_{r \in\ E}{p_{ir}^{(k)}{\ \ \ p}_{ij}^{(n-k)}} $$

 <div align="center">
    Formula 5. Probabilidad en n pasos
</div>

E : Representa al espacio de los estados
 

En una matriz de transición, la cadena de márkov de $n$ estados, representa la matriz de n x n donde todos los registros que son no negativos y con la respectiva propiedad en la cual la sema de los registros de cada columna o fila dan el resultado de 1.

$p_{ij}$ : Es la probabilidad de transicion desde el estado $i$ al estado $j$

Por lo tanto, se agrupan en la matriz de transicion de la cadena de márkov, que dando asi: 

$$  P\ =\ \left[\begin{matrix}P_{00}&P_{01}&...\\P_{10}&P_{11}&...\\...&\cdots&...\\\end{matrix}\right]\ \ =\ (P_{i\ j})\ i,\ j\ \in\ S $$

 <div align="center">
    Formula 6. Agrupación de la matríz de transición
</div>


#### 2.1.4. Distribución  Binomial

La distribución binomial, representa la probabilidad donde nos cuenta el porcentaje donde se predice cual es posible obtener un resultado optimo entre dos estados al realizar un numero n de pruebas realizadas. Esta probabilidad no puede ser mas grande que 1 y menos dar un resultado negativo.

En esta distribución, los valores de p (x; n, p) para x = 0,1,2…n son los términos sucesivos de la expansión binomial de $\left[(1\ -\ p)\ +\ p\right]$

$$P(k,\ n;\ p)\ =\ \binom{n}{k}\ p^k{(1\ -\ p)}^{n\ -\ k}\ $$

 <div align="center">
    Formula 7. Distribución Binomial
</div>


### 2.2. Desarrollo Computacional

Para el desarrollo de computacional relacionado a este informe se uso el lenguaje de programación Python 3.10.7 y las siguientes librerías:

* numpy - se especializa en el cálculo, transformación y análisis de datos numéricos.
* factorial - librería nativa de Python para calcular el factorial de un número
* product - genera un producto iterable para evitar tener ciclos for anidados

In [ ]:
from math import factorial
import numpy as np
from itertools import product

#### 2.2.1 Función Binomial

In [ ]:
class Binomial:
    def __init__(self, n: int, p: float):
        self.n = n  # espacio muestral
        self.p = p  # probabilidad

    def _combination(self, n: int, x: int) -> float:
        '''Calcula la combinatoria de dos números'''
        if x > n:
            raise ValueError("n debe ser mayor o igual a x")
        return 1 if n == x else factorial(n) / (factorial(x) * factorial(n - x))

    def pmf(self, k: int) -> float:
        '''Calcula la distribución binomial, en el paso k'''
        if k > self.n:
            raise ValueError("n debe ser mayor o igual a k")

        if self.p < 0 and self.p > 1:
            return 0

        return self._combination(self.n, k) * pow(self.p, k) * pow(1 - self.p, self.n - k)

    def cdf(self, k: int) -> float:
        '''Calcula la función acumulativa de la distribución binomial, en el paso k'''
        if k > self.n:
            raise ValueError("n debe ser mayor o igual a k")

        return sum(self.pmf(i) for i in range(k + 1))

#### 2.2.2 Matríz de Transición

Los siguientes métodos calcular los valores de las celdas de la matríz de transición (desde celdas iniciales, finales, centrales, a la izquierda y a la derecha)

In [ ]:
def calculate_first_row(matrix, k: int, n: int, p_in: float):
    matrix.append(Binomial(n, p_in).pmf(k))

def calculate_first_cell(
    matrix,
    k: int,
    n: int,
    p_in: float,
    p_out: float,
    i:int,
    total_sample: int
):
    matrix.append(
        Binomial(i, p_out).pmf(k + n)
        * Binomial(total_sample - n, p_in).pmf(k)
    )

def calculate_left_cell(matrix, k: int, n: int, p_out: float):
    matrix.append(Binomial(n, p_out).pmf(k))

def calculate_center_cell(
    matrix,
    k: int,
    n: int,
    p_in: float,
    p_out: float,
    total_sample: int
):
    matrix.append(
        Binomial(n, p_out).pmf(k)
        * Binomial(n, p_in).pmf(k)
        + Binomial(n, p_out).pmf(0)
        * Binomial(total_sample - n, p_in).pmf(0)
    )

def calculate_right_cell(
    matrix,
    k: int,
    n: int,
    p_in: float,
    p_out: float,
    total_sample: int
):
    matrix.append(
        Binomial(n, p_out).pmf(0)
        * Binomial(total_sample - n, p_in).pmf(np.abs(k - n))
    )

def calculate_last_cell(matrix, k: int, n: int, p_out: float):
    matrix.append(Binomial(n, p_out).pmf(k))

In [ ]:
def calculate_transition_matrix(matrix, total_sample: int, p_in: float, p_out: float):
    '''Calcular y llenar la matríz de transición'''
    for i, j in product(range(total_sample + 1), range(total_sample + 1)):
        if i == 0:
            calculate_first_row(matrix, j, total_sample, p_in)
        elif i == total_sample:
            j = i - j
            calculate_last_cell(matrix, j, i, p_out)
        elif j == 0 and i > 0:
            calculate_first_cell(matrix, j, i, p_in, p_out, i, total_sample)
        elif j == i and i > 0:
            calculate_center_cell(matrix, j, i, p_in, p_out, total_sample)
        elif j < i and i > 0:
            calculate_left_cell(matrix, j, i, p_out)
        elif j > i > 0:
            calculate_right_cell(matrix, j, i, p_in, p_out, total_sample)

In [ ]:
def print_transition_matrix(matrix, total_sample: int):
    '''Formatea e imprime la matríz de transición'''
    matrix_aux = np.array(matrix).reshape((total_sample + 1, total_sample + 1))
    matrix_aux = np.round(matrix_aux, decimals=4)
    print(matrix_aux)

    matrix_sum = np.sum(matrix_aux, axis=1)
    matrix_sum = np.round(matrix_sum, decimals=0)
    print(f'Sum matrix: {matrix_sum}')

## 3. Problemas

Un ordenador compartido por n usuarios.
Donde n = 2 hasta 10, con las probabilidades de que un usuario pueda desconectarse con 0.3 y se puede conectar con probabilidad de 0.4.
Modelamos con una cadena de márkov X(t) que da el numero de usuarios conectados.


## 4. Resultados

### 4.1 Ejemplo con 3 usuarios
Se puede apreciar en la siguiente tabla la matríz de transición para 3 usuarios en el sistema.

In [ ]:
sample = 3
matrix = []
p_in = 0.4
p_out = 0.3

calculate_transition_matrix(matrix, sample, p_in, p_out)
print_transition_matrix(matrix, sample)

[[0.216  0.432  0.288  0.064 ]
 [0.108  0.372  0.336  0.112 ]
 [0.054  0.42   0.3084 0.196 ]
 [0.027  0.189  0.441  0.343 ]]
Sum matrix: [1. 1. 1. 1.]


 <div align="center">
    Tabla 1. Matríz de transición con 3 usuarios
</div>


### 4.2 Ejemplo con 4 usuarios
Se puede apreciar en la siguiente tabla la matríz de transición para 4 usuarios en el sistema.

In [ ]:
sample = 4
matrix = []
p_in = 0.4
p_out = 0.3

calculate_transition_matrix(matrix, sample, p_in, p_out)
print_transition_matrix(matrix, sample)

[[0.1296 0.3456 0.3456 0.1536 0.0256]
 [0.0648 0.2712 0.3024 0.2016 0.0448]
 [0.0324 0.42   0.1908 0.2352 0.0784]
 [0.0162 0.441  0.189  0.2075 0.1372]
 [0.0081 0.0756 0.2646 0.4116 0.2401]]
Sum matrix: [1. 1. 1. 1. 1.]


 <div align="center">
    Tabla 2. Matríz de transición con 4 usuarios
</div>


### 4.3 Ejercicio dinámico
El usuario debe de ingresar cuantos usuarios habrán en el sistema y se generará la matríz de transición

In [ ]:
sample = int(input('Cantidad de usuarios: '))
matrix = []
p_in = 0.4
p_out = 0.3

if 2 <= sample <= 10: 
  calculate_transition_matrix(matrix, sample, p_in, p_out)
  print_transition_matrix(matrix, sample)

Cantidad de usuarios: 3
[[0.216  0.432  0.288  0.064 ]
 [0.108  0.372  0.336  0.112 ]
 [0.054  0.42   0.3084 0.196 ]
 [0.027  0.189  0.441  0.343 ]]
Sum matrix: [1. 1. 1. 1.]


 <div align="center">
    Tabla 3. Matríz de transición dinámica 
</div>


## 5. Conclusiones

Se resalta la gran importancia que presenta las cadenas de markov al momento de establecer y determinar las probabilidades dadas que sobresalen en los resultados obtenidos; nos muestra que es una herramienta útil para llevar a cabo un eficaz rendimiento al momento de establecer las conexiones y las desconexiones de los usuarios en una computadora. A futuro podemos ver como un sistema basado en lograr crear estrategias logrando analizar las probabilidades, poder resolver problemas en el mundo real y generar gran impacto de forma positiva en cualquier ámbito requerido.

## 6. Referencias

- [Cadenas de Márkov](file:///D:/documentos/Downloads/Chain%20Markov.pdf)